#consul服务端口
server:
  port: 80

spring:
  application:
    name: consul-consumer-order

  #consul注册中心
  cloud:
    consul:
      host: 8.129.122.251
      port: 8500
      discovery:
        #hostname:127.0.0.1
        service-name: ${spring.application.name}
        #hostname: 8.129.122.251
        heartbeat:
          enabled: true