server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wjlrn/springcloud-config.git #GitHub上面的git仓库名字
          #搜索目录
          search-paths:
            - springcloud-config
          username: wjlrn
          password: 369824lrn#
          skip-ssl-validation: true
      #读取分支
      label: master
  rabbitmq:
    host: 8.129.122.251
    port: 5672
    username: guest
    password: guest

#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: "bus-refresh"

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka